# Generated by Django 4.2.7 on 2023-12-12 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminDataModel',
            fields=[
                ('admin_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('admin_username', models.CharField(max_length=100)),
                ('admin_password', models.CharField(max_length=100)),
                ('admin_phone_number', models.CharField(max_length=100)),
                ('admin_email', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'admin_data_table',
            },
        ),
        migrations.CreateModel(
            name='MainCategoryModel',
            fields=[
                ('main_category_id', models.IntegerField(primary_key=True, serialize=False)),
                ('main_category_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'main_category_table',
            },
        ),
        migrations.CreateModel(
            name='StateModel',
            fields=[
                ('state_id', models.IntegerField(primary_key=True, serialize=False)),
                ('state_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'state_data_table',
            },
        ),
        migrations.CreateModel(
            name='SubCategoryModel',
            fields=[
                ('sub_category_id', models.IntegerField(primary_key=True, serialize=False)),
                ('sub_category_name', models.CharField(max_length=100)),
                ('main_category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminApp.maincategorymodel')),
            ],
            options={
                'db_table': 'sub_category_table',
            },
        ),
        migrations.CreateModel(
            name='DistrictsModel',
            fields=[
                ('district_id', models.IntegerField(primary_key=True, serialize=False)),
                ('district_name', models.CharField(max_length=100)),
                ('state_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminApp.statemodel')),
            ],
            options={
                'db_table': 'districts_data_table',
            },
        ),
    ]
