# Generated by Django 4.2.7 on 2023-12-13 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0002_donationcategorymodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategorymodel',
            name='sub_category_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
