# Generated by Django 4.2.7 on 2023-12-12 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('AdminApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDataModel',
            fields=[
                ('create_at', models.DateTimeField(auto_created=True)),
                ('user_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=200)),
                ('user_password', models.CharField(max_length=200)),
                ('user_phone_number', models.CharField(max_length=100)),
                ('user_status', models.CharField(default='Active', max_length=100)),
            ],
            options={
                'db_table': 'user_data_table',
            },
        ),
        migrations.CreateModel(
            name='UserPostModel',
            fields=[
                ('post_create_at', models.DateTimeField(auto_created=True)),
                ('post_id', models.IntegerField(primary_key=True, serialize=False)),
                ('post_title', models.CharField(max_length=250)),
                ('post_description', models.TextField()),
                ('post_quantity', models.IntegerField()),
                ('post_pick_up_time', models.DateField()),
                ('post_end_on', models.DateTimeField(null=True)),
                ('post_address', models.TextField()),
                ('post_images', models.ImageField(null=True, upload_to='images/')),
                ('user_contact_number', models.CharField(max_length=100)),
                ('post_comments', models.CharField(max_length=300, null=True)),
                ('post_status', models.CharField(default='Active', max_length=100)),
                ('post_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminApp.districtsmodel')),
                ('post_sub_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminApp.subcategorymodel')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserApp.userdatamodel')),
            ],
            options={
                'db_table': 'user_post_table',
            },
        ),
        migrations.CreateModel(
            name='UserImageModel',
            fields=[
                ('user_image_id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_image', models.ImageField(upload_to='')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserApp.userdatamodel')),
            ],
            options={
                'db_table': 'user_image_table',
            },
        ),
        migrations.CreateModel(
            name='UserDonationModel',
            fields=[
                ('donation_create_at', models.DateTimeField(auto_created=True)),
                ('donation_id', models.IntegerField(primary_key=True, serialize=False)),
                ('donation_title', models.CharField(max_length=400)),
                ('donation_description', models.TextField()),
                ('donation_end_date', models.DateTimeField()),
                ('donation_address', models.CharField(max_length=500)),
                ('donation_images', models.ImageField(null=True, upload_to='images/')),
                ('user_contact_number', models.CharField(max_length=100)),
                ('donation_comments', models.CharField(max_length=500)),
                ('donation_status', models.CharField(default='Pending', max_length=100)),
                ('donation_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminApp.subcategorymodel')),
                ('donation_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminApp.districtsmodel')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserApp.userdatamodel')),
            ],
            options={
                'db_table': 'user_donation_table',
            },
        ),
    ]
