# Generated by Django 4.2.7 on 2023-12-12 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0002_alter_userdonationmodel_donation_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdatamodel',
            name='create_at',
            field=models.DateField(auto_created=True),
        ),
    ]
